{"name":"arthemeticExceptionTesting","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"/ by zero","trace":"java.lang.ArithmeticException: / by zero\n\tat JavaPractice.ExceptionTest.arthemeticExceptionTesting(ExceptionTest.java:18)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)\n\tat org.testng.internal.Invoker.invokeMethod(Invoker.java:583)\n\tat org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)\n\tat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)\n\tat org.testng.TestRunner.privateRun(TestRunner.java:648)\n\tat org.testng.TestRunner.run(TestRunner.java:505)\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:455)\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:364)\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1137)\n\tat org.testng.TestNG.runSuites(TestNG.java:1049)\n\tat org.testng.TestNG.run(TestNG.java:1017)\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1590590512265,"stop":1590590512310,"uuid":"72e2fe9a-d603-4a36-9cb9-76b534bc3782","historyId":"865a4d53c7d38bf18fbb50a1dfb35d64","fullName":"JavaPractice.ExceptionTest.arthemeticExceptionTesting","labels":[{"name":"package","value":"JavaPractice.ExceptionTest"},{"name":"testClass","value":"JavaPractice.ExceptionTest"},{"name":"testMethod","value":"arthemeticExceptionTesting"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"DevPreactice"},{"name":"subSuite","value":"JavaPractice.ExceptionTest"},{"name":"host","value":"apples-MacBook-Pro.local"},{"name":"thread","value":"8444@apples-MacBook-Pro.local.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[]}